### ISSUE TITLE
[ADD Media Browser Support]

### ISSUE THREAD

**Issue by thundergreen** [definitio/ha-sox#2]
Hello,

I was just wondering if it wuld be possible to integrate media browser. My idea is to play music from my media browser directly on the robot ?

**Comment by definitio** [comment]
It will be very hard to implement because SoX doesn't support media libraries.

**Comment by thundergreen** [comment]
O..ok didn't know ..well if you would be interested..I'd of course wait . If not please close this issue ☺️

**Comment by definitio** [comment]
@thundergreen Hi, are you still interested? It should work now.

**Comment by thundergreen** [comment]
just tested.. but no sound coming out of the robot.. i guess i have to make a call to the robot via cli. let me test and report

**Comment by thundergreen** [comment]
i think i am still facing https://github.com/definitio/ha-sox/issues/4 but i now added at startup of homeassistant to run the sh script and hope it will fix it

**Comment by thundergreen** [comment]
Cool I already updated but did not test .let me test and report later 👍🤞

definitio ***@***.***> schrieb am Fr., 20. Mai 2022, 19:55:
